# Mel-filterbank
MEL_WINDOW_LENGTH = 25 # In milliseconds
MEL_WINDOW_STEP = 10 # In milliseconds
MEL_N_CHANNELS = 40

# Model
HIDDEN_NODES = 768
PROJECTION_SIZE = 256
NUM_LAYERS = 3

SPEAKERS_PER_BATCH = 64
UTTERANCES_PER_SPEAKER = 10

INITIAL_LEARNING_RATE = 0.01
STEPS_PER_HALVING = 30_000_000

L2_NORM_CLIP = 3

PROJECTION_GRADIENT_SCALE = 0.5

# Apparently this helped smooth convergence
SIMILARITY_WEIGHT_INIT = 10.
SIMILARITY_BIAS_INIT = -5.