# Mel-filterbank
MEL_WINDOW_LENGTH = 25 # In milliseconds
MEL_WINDOW_STEP = 10 # In milliseconds
MEL_N_CHANNELS = 40

# Audio
SAMPLING_RATE = 16000
PARTIALS_N_FRAMES = 160
INFERENCE_N_FRAMES = 80

# Voice Activation Detection
VAD_WINDOW_LENGTH = 30
VAD_MOVING_AVERAGE_WIDTH = 8
VAD_MAX_SILENCE_LENGTH = 6

# Audio Volume Normalization
AUDIO_NORM_TARGET_DBFS = -30

# Model
HIDDEN_NODES = 768
PROJECTION_SIZE = 256
NUM_LAYERS = 3

SPEAKERS_PER_BATCH = 64
UTTERANCES_PER_SPEAKER = 10

LEARNING_RATE_INIT = 1e-4
STEPS_PER_HALVING = 30_000_000

L2_NORM_CLIP = 3

PROJECTION_GRADIENT_SCALE = 0.5

# Apparently this helped smooth convergence
SIMILARITY_WEIGHT_INIT = 10.
SIMILARITY_BIAS_INIT = -5.